const data = {
  products: [
    {
      _id: 1,
      name: "Nike Slim Shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "Nike",
      numReviews: 11,
      rating: 4.5,
      description: "High Quality Product",
    },
    {
      _id: 2,
      name: "Nike Fat Shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 111,
      brand: "Nike",
      numReviews: 22,
      rating: 4.5,
      description: "High Quality Product",
    },
    {
      _id: 3,
      name: "Addidas Slim Shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 109,
      brand: "Addidas",
      numReviews: 2,
      rating: 1.5,
      description: "High Quality Product",
    },
    {
      _id: 4,
      name: "Addidas Slim Pants",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 103,
      brand: "Addidas",
      numReviews: 3,
      rating: 2.5,
      description: "High Quality Product",
    },
    {
      _id: 5,
      name: "Addidas Fat Pants",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 99,
      brand: "Addidas",
      numReviews: 2,
      rating: 3.5,
      description: "High Quality Product",
    },
    {
      _id: 6,
      name: "Addidas Hefty Pants",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 100,
      brand: "Addidas",
      numReviews: 22,
      rating: 5,
      description: "High Quality Product",
    },
  ],
};
export default data;
